# Problem 1

In [11]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
a = np.random.randint(0,10, size=5)
# 3 - matris'in boyutunu öğrenin
print(a.size)
# 4 - matris'i yeniden boyutlandırın
a.reshape(5,1)

5


array([[5],
       [4],
       [4],
       [9],
       [4]], dtype=int32)

# Problem 2

In [22]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
b = np.arange(1,10,2)
# 2 - Oluşturduğunuz matrisi parçalayın
k,l,m = np.split(b, [2,4])
# 3 - Parçalanmış matrisleri birleştirin
np.concatenate([k,l,m], axis=0)

array([1, 3, 5, 7, 9])

# Problem 3

In [41]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
c = np.arange(5,100,2)
z= np.random.randint(5, len(c), size=10)
rand_num = c[z]
print(rand_num)
# 2 - matris'in özelliklerini inceleyin
print(c.ndim)
print(c.size)
print(c.shape)
print(c.dtype)

[91 87 81 19 63 43 25 41 87 45]
1
48
(48,)
int64
