# Problem 1 

In [2]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
c = np.random.randint(1,100,5)
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
np.sort(c)

array([ 4,  9, 50, 63, 75], dtype=int32)

# Problem 2

In [3]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
np.array([10,15,30,45,60])

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
np.arange(5,15)
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
np.arange(50,100,5)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
np.zeros(10)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
np.ones(10)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
np.linspace(0,100,5)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
np.random.randint(10,30,size=5)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
np.random.uniform(-1, 1,size=10)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
b = np.random.randint(-50,50,size=[3,5])
print(b)
# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
print(f"satır: {b.sum(axis=1)}")
print(f"sütun: {b.sum(axis=0)}")
# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
b.max()
b.min()
b.mean()
# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
np.unravel_index(np.argmax(b), b.shape)

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
d = np.arange(10,20)
print(d[:3])
# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(d[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.
print(b[0,:])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(b[1,2])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(b[:,0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(b*2)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
cift_sayi = [number for row in b for number in row if number > 0 and number % 2 == 0]
print(cift_sayi)

[[ 32  32  -8  -3  28]
 [ -6 -49 -44  -5  31]
 [ 20   6 -29 -16 -50]]
satır: [ 81 -73 -69]
sütun: [ 46 -11 -81 -24   9]
[10 11 12]
[19 18 17 16 15 14 13 12 11 10]
[32 32 -8 -3 28]
-44
[32 -6 20]
[[  64   64  -16   -6   56]
 [ -12  -98  -88  -10   62]
 [  40   12  -58  -32 -100]]
[np.int32(32), np.int32(32), np.int32(28), np.int32(20), np.int32(6)]
